const images = {
  logoHeaderW: '/assets/images/ic-logo-header-w@3x.png',
  logoHeaderb: '/assets/images/ic-logo-header-b@3x.png',
  logoFooter: '/assets/images/ic-logo-footer-g@3x.png',
  buisiness: {
    hardware: '/assets/images/img-business-hardware.webp',
    webApp: '/assets/images/img-business-web-app.webp',
    ai: '/assets/images/img-business-ai.webp',
  },
  partnersLogo: {
    logo1: '/assets/images/logo/logo-01.png',
    logo2: '/assets/images/logo/logo-02.png',
    logo3: '/assets/images/logo/logo-03.png',
    logo4: '/assets/images/logo/logo-04.png',
    logo5: '/assets/images/logo/logo-05.png',
    logo6: '/assets/images/logo/logo-06.png',
    logo7: '/assets/images/logo/logo-07.png',
    logo8: '/assets/images/logo/logo-08.png',
    logo9: '/assets/images/logo/logo-09.png',
    logo10: '/assets/images/logo/logo-10.png',
    logo11: '/assets/images/logo/logo-11.png',
    logo12: '/assets/images/logo/logo-12.png',
  },
  partnersBackground: '/assets/images/img-partners@3x.png',
  mainVideo: '/assets/images/main-video.mp4',
  contact: '/assets/images/img-contact-us.webp',
  contactDetail: '/assets/images/img-contact-us-detail.webp',
  hisotry: '/assets/images/img-history.webp',
  partners: '/assets/images/img-partners@3x.png',
  downloadW: '/assets/images/ic-download-w@3x.png',
  downloadB: '/assets/images/ic-download-b@3x.png',
  rightBtnW: '/assets/images/ic-right-btn-w@3x.png',
  rightBtnB: '/assets/images/ic-right-btn-b@3x.png',
  leftBtnW: '/assets/images/ic-left-btn-w@3x.png',
  leftBtnB: '/assets/images/ic-left-btn-b@3x.png',
  pdf: '/assets/pdf/WIM_COMPANY_PORTFOLIO.pdf',
  privacy: '/terms/privacy.html',
  terms: '/terms/terms.html',
};

export default images;
